GRANT ALL PRIVILEGES ON DATABASE otus_db TO otus;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO otus;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO otus;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO otus;