version: '3'
services:
  postgres:
    image: "postgres:13"
    container_name: 'java-postgres-s08'
    ports:
      - "6432:5432"
    environment:
      - 'POSTGRES_DB=otus_db'
      - 'POSTGRES_USER=otus'
      - 'POSTGRES_PASSWORD=otus'
    volumes:
      - ./src/main/resources/db/init.sql:/docker-entrypoint-initdb.d/init.sql