server:
  port: 8080

logging:
  level:
    root: ERROR

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/myDB
    username: admin
    password: admin
  sql:
    init:
      mode: always
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate  # or none
    show-sql: true
    properties:
      hibernate:
        format_sql: false
  messages:
    encoding: UTF-8
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: public

management:
  endpoints:
    web:
      exposure:
        include: "health"
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true