version: '3'
services:
  app:
    container_name: 'app'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    # Will rewrite properties in application.yml
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:6432/otus_db
      - SPRING_DATASOURCE_USERNAME=otus
      - SPRING_DATASOURCE_PASSWORD=otus
  postgres:
    image: "postgres:13"
    container_name: 'java-postgres'
    ports:
      - "6432:5432"
    environment:
      - 'POSTGRES_DB=otus_db'
      - 'POSTGRES_USER=otus'
      - 'POSTGRES_PASSWORD=otus'
    volumes:
      - ./src/main/resources/db/init.sql:/docker-entrypoint-initdb.d/init.sql
