logging:
  level:
    root: ERROR

spring:
  datasource:
    url: jdbc:h2:mem:testdb
#    url: jdbc:postgresql://localhost:5432/otusDB
#    username: otus
#    password: otus
  sql:
    init:
      mode: always
#      data-locations: data.sql
#      chema-locations: schema.sql
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate

    show-sql: true

    properties:
      hibernate:
        format_sql: false

  messages:
    encoding: UTF-8
