server:
  port: 8080

logging:
  level:
    root: ERROR

spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:postgresql://localhost:6432/otus_db
    username: otus
    password: otus
  sql:
    init:
      mode: always
  messages:
    encoding: UTF-8
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: public
